<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Ez.Generic.DataSync.Core.csproj" />
    <ProjectReference Include="..\..\Extensions\Ez.Generic.DataSync.Extensions.csproj" />
  </ItemGroup>

</Project>
